import { describe, expect, it } from "@effect/vitest";
import Pusher from "pusher";
import * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import {
  channelAuthorization,
  hmacSha256Hex,
  md5Hex,
  userAuthentication,
} from "../src/pusher/crypto.ts";
import {
  classifyChannel,
  connectionEstablished,
  encodeServerEvent,
  eventDataSize,
  isValidChannelName,
  parseClientFrame,
} from "../src/pusher/protocol.ts";

describe("Pusher wire protocol", () => {
  it.effect("emits the required double-encoded connection handshake", () =>
    Effect.gen(function* () {
      const event = yield* connectionEstablished("1234.5678", 120);
      const encoded = yield* encodeServerEvent(event);
      const decoded = yield* Schema.decodeEffect(
        Schema.fromJsonString(
          Schema.Struct({
            data: Schema.String,
            event: Schema.String,
          }),
        ),
      )(encoded);
      expect(decoded).toEqual({
        data: '{"activity_timeout":120,"socket_id":"1234.5678"}',
        event: "pusher:connection_established",
      });
    }),
  );

  it.effect("decodes object and string client data through Effect Schema", () =>
    Effect.gen(function* () {
      const objectFrame = yield* parseClientFrame(
        '{"event":"client-message","channel":"private-room","data":{"x":1}}',
      );
      const stringFrame = yield* parseClientFrame(
        '{"event":"client-message","channel":"private-room","data":"raw"}',
      );
      expect(objectFrame.data).toEqual({ x: 1 });
      expect(stringFrame.data).toBe("raw");
    }),
  );

  it("classifies every Pusher channel family", () => {
    expect(classifyChannel("orders")).toEqual({ cache: false, kind: "public" });
    expect(classifyChannel("cache-orders")).toEqual({ cache: true, kind: "public" });
    expect(classifyChannel("private-orders")).toEqual({ cache: false, kind: "private" });
    expect(classifyChannel("private-cache-orders")).toEqual({ cache: true, kind: "private" });
    expect(classifyChannel("presence-orders")).toEqual({ cache: false, kind: "presence" });
    expect(classifyChannel("presence-cache-orders")).toEqual({ cache: true, kind: "presence" });
    expect(classifyChannel("private-encrypted-orders")).toEqual({
      cache: false,
      kind: "encrypted",
    });
    expect(classifyChannel("private-encrypted-cache-orders")).toEqual({
      cache: true,
      kind: "encrypted",
    });
  });

  it("enforces documented channel names and UTF-8 byte sizes", () => {
    expect(isValidChannelName("a".repeat(164))).toBe(true);
    expect(isValidChannelName("a".repeat(165))).toBe(false);
    expect(isValidChannelName("room_1-=@,.;")).toBe(true);
    expect(isValidChannelName("room/1")).toBe(false);
    expect(eventDataSize("😀")).toBe(4);
  });
});

describe("Pusher signatures", () => {
  const key = "278d425bdf160c739803";
  const secret = "7ad3773142a6692b25b8";

  it("matches the official private-channel vector", () => {
    expect(channelAuthorization(key, secret, "1234.1234", "private-foobar")).toBe(
      "278d425bdf160c739803:58df8b0c36d6982b82c3ecf6b4662e34fe8c25bba48f5369f135bf843651c3a4",
    );
  });

  it("matches the official user-authentication vector", () => {
    expect(userAuthentication(key, secret, "1234.1234", '{"id":"12345"}')).toBe(
      "278d425bdf160c739803:4708d583dada6a56435fb8bc611c77c359a31eebde13337c16ab43aa6de336ba",
    );
  });

  it("matches the official REST body and signature vector", () => {
    const body = new TextEncoder().encode(
      '{"name":"foo","channels":["project-3"],"data":"{\\"some\\":\\"data\\"}"}',
    );
    expect(md5Hex(body)).toBe("ec365a775a4cd0599faeb73354201b6f");
    const canonical =
      "POST\n/apps/3/events\n" +
      "auth_key=278d425bdf160c739803&auth_timestamp=1353088179&auth_version=1.0&" +
      "body_md5=ec365a775a4cd0599faeb73354201b6f";
    expect(hmacSha256Hex(secret, canonical)).toBe(
      "da454824c97ba181a32ccc17a72625ba02771f50b50e1e7430e47a1f3f457e6c",
    );
  });

  it("accepts signatures generated by the official Node server SDK", () => {
    const pusher = new Pusher({ appId: "3", cluster: "mt1", key, secret, useTLS: true });
    expect(pusher.authorizeChannel("1234.1234", "private-foobar")).toEqual({
      auth: channelAuthorization(key, secret, "1234.1234", "private-foobar"),
    });
  });
});
